export type WolfStage =
	"Newborn"
	| "EyesOpen"
	| "FirstSteps"
	| "OutsideDen"
	| "FirstHowl"
	| "Rendezvous"
	| "HuntTraining"
	| "YoungAdult"
	| "FullGrown"

return {
	Newborn = "Newborn",
	EyesOpen = "EyesOpen",
	FirstSteps = "FirstSteps",
	OutsideDen = "OutsideDen",
	FirstHowl = "FirstHowl",
	Rendezvous = "Rendezvous",
	HuntTraining = "HuntTraining",
	YoungAdult = "YoungAdult",
	FullGrown = "FullGrown",
}
